"""Initial Migration

Revision ID: c570cab861ef
Revises: 
Create Date: 2021-12-08 21:51:44.134434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c570cab861ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('book_name')
    )
    op.create_table('certs',
    sa.Column('cert_id', sa.Integer(), nullable=False),
    sa.Column('cert_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('cert_id'),
    sa.UniqueConstraint('cert_name')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('certifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('cert_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cert_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('cert_id', name='certifications_pkey'),
    sa.UniqueConstraint('cert_name', name='certifications_cert_name_key')
    )
    op.drop_table('flasklogin-users')
    op.drop_table('courses')
    op.drop_table('certs')
    op.drop_table('books')
    # ### end Alembic commands ###
